### PR TITLE
rebase to alpine 3.8 and use buildstage type build

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by sparklyballs** [comment]
jenkins test this please

**Review by CHBMB — COMMENTED** [review]
Line 10?  Why set TZ as Oslo?

**Comment by sparklyballs** [comment]
blame @tobbenb

**Comment by sparklyballs** [comment]
plus it's a build time only setting as arg isn't passed to the container.

**Comment by tobbenb** [comment]
Haha. Yeah I'm the one to blame. It was needed for something to build on arm. Don't remember what now... Should have used Copenhagen?

**Review by aptalca — APPROVED** [review]

**Pull request merged**
